Acheteur_Malin/acheteurmalin/categories/routes.py
from flask import render_template, url_for, flash, redirect, request
from acheteurmalin import mongo
from acheteurmalin.main.forms import EnregistrerForm 
from PIL import Image
import secrets
import os
from flask import Blueprint, current_app

categories = Blueprint('categories', __name__)

@categories.route("/")
def accueil():
	objet=[]
	objet=mongo.db.Objet.find()
	return render_template('accueil.html', objet=objet, title='Le site de comparatif qui conseil vos achats')

@categories.route("/hightech")
def hightech():
	objet=[]
	objet=mongo.db.Objet.find({'categorie':'hightech'})
	return render_template('hightech.html', title=' conseil et comparatif achat Hightech', objet=objet)

@categories.route("/electromenager")
def electromenager():
	objet=[]
	objet=mongo.db.Objet.find({'categorie':'elecctromenager'})
	return render_template('electromenager.html', title=' conseil et comparatif achat Hightech', objet=objet)


@categories.route("/musique")
def musique():
	objet=[]
	objet=mongo.db.Objet.find({'categorie':'musique'})
	return render_template('musique.html', title=' conseil et comparatif achat Hightech', objet=objet)


@categories.route("/telephone")
def telephone():
	objet=[]
	objet=mongo.db.Objet.find({'categorie':'telephone'})
	return render_template('telephone.html', title=' conseil et comparatif achat Hightech', objet=objet)

Acheteur_Malin/acheteurmalin/main/routes.py
from flask import render_template, url_for, flash, redirect, request
from acheteurmalin import mongo
from acheteurmalin.main.forms import EnregistrerForm 
from PIL import Image
import secrets
import os
from flask import Blueprint, current_app


main = Blueprint('main', __name__)

@main.route("/mentionslegales")
def mentionslegales():
	return render_template('mentionslegales.html')


def save_picture(form_picture):
	random_hex = secrets.token_hex(8)
	_, f_ext = os.path.splitext(form_picture)
	picture_fn = random_hex + f_ext
	picture_path = os.path.join(current_app.root_path, 'static/objet_photo', picture_fn)
	
	output_size = (150, 150)
	i = Image.open("acheteurmalin/static/image/" + form_picture)
	i.thumbnail(output_size) 
	i.save(picture_path)
	
	path = 'static/objet_photo/'+ picture_fn

	
	return path

@main.route("/enregistrer", methods=['GET', 'POST'])
def enregistrer():
	form = EnregistrerForm()
	if form.validate_on_submit():
		if form.image_file.data:
			image_file = save_picture(form.image_file.data)
		objet = {'nom' : form.nom.data, 'image_file' : image_file , 'affiliation' : form.affiliation.data, 'commentaire': form.commentaire.data, 'categorie' : form.categorie.data}
		mongo.db.Objet.insert_one(objet)
		flash(f'L objet à été ajouté', 'success')
		return redirect(url_for('main.enregistrer'))
	return render_template('enregistrer.html', title='enregistrer', form=form)


Acheteur_Malin/acheteurmalin/templates/accueil.html
{% extends "categories.html" %}
{% block infotop %}
	
	

	<div class="infocontainer">
		<h1 class="texte h1">AcheteurMalin :   Information, conseil et comparatif achat.</h1>
		<img class= "courbe contenu" src="static/image/téléchargement.png" alt="courbe statistiques des prix">	
		<div class = infocontainer2>
			<H2 class="texte contenu">Retrouvez les objets les plus vendus du moment dans 			chaque catégorie. Comparez les au courbes des prix
				enregistré pour savoir combien vous devriez dépenser et ainsi éffectué un achat malin. En effet les statistiques de 
				masse permette de se faire une idée réaliste et pertinente de l’investissement à éffectuer.
			</H2>
		</div>
	</div>


{% endblock infotop %}

Acheteur_Malin/acheteurmalin/templates/categories.html
{% extends "layout.html" %}
{% block content %}
	
	{% block infotop %}{% endblock %}

	<div class="objetcontainer">
		{% for object in objet %}
			<div class="objet">
				<div class=containerphoto>
					<img class= "photo" src="{{ object.image_file }}" alt="photo de l'{{ object.nom }}">
				<!--	<div style="background-size: contain; background:no-repeat url({{ object.image_file }});" class="photo"></div> -->
				</div>
				<h3 class="texteobjet nomobjet" href=#>{{ object.nom }}</h3> 
				<a class="texteobjet prixobjet" href=#>{{ object.affiliation }}</a>	
				<a class="texteobjet commentaire" href=#>{{ object.commentaire }}</a>  
			</div>
		{% endfor %}

	</div>

{% endblock content %}

Acheteur_Malin/acheteurmalin/templates/electromenager.html
{% extends "categories.html" %}
{% block infotop %}
	
	

	<div class="infocontainer">
		<h2 class="texte nomarge">AcheteurMalin : </h2>
		<H1 class="texte h1">Information, conseil et comparatif achat.</H1>
		<img class= "courbe contenu" src="static/image/téléchargement.png" alt="courbe statistiques des prix">	
		<div class = infocontainer2>
			<H2 class="texte contenu">Retrouvez les objets les plus vendus du moment dans 			chaque catégorie. Comparez les au courbes des prix
				enregistré pour savoir combien vous devriez dépenser et ainsi éffectué un achat malin. En effet les statistiques de 
				masse permette de se faire une idée réaliste et pertinente de l’investissement à éffectuer.
			</H2>
		</div>
	</div>


{% endblock infotop %}

Acheteur_Malin/acheteurmalin/templates/enregistrer.html
{% extends "layout.html" %}
{% block content %}
	<div class="content-section">
		<form method="POST" action="">
			{{ form.hidden_tag() }} <!-- csrf attaque -->
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Enregistre ton objet</legend>
				<div class="form-group">
					{{ form.nom.label(class="form-control-label") }}

					{% if form.nom.errors %}
						{{ form.nom(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.nom.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
							
					{% else %}
						{{ form.nom(class="form-control form-control-lg") }}						
					{% endif %}


				</div>
				<div class="form-group">
					{{ form.categorie.label(class="form-control-label") }}

					{% if form.categorie.errors %}
						{{ form.categorie(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.categorie.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
							
					{% else %}
						{{ form.categorie(class="form-control form-control-lg") }}						
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.image_file.label(class="form-control-label") }}

					{% if form.image_file.errors %}
						{{ form.image_file(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.image_file.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
							
					{% else %}
						{{ form.image_file(class="form-control form-control-lg") }}						
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.affiliation.label(class="form-control-label") }}

					{% if form.affiliation.errors %}
						{{ form.affiliation(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.affiliation.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
							
					{% else %}
						{{ form.affiliation(class="form-control form-control-lg") }}						
					{% endif %}
				</div>
				<div class="form-group">
					{{ form.commentaire.label(class="form-control-label") }}

					{% if form.commentaire.errors %}
						{{ form.commentaire(class="form-control form-control-lg is-invalid") }}
						<div class="invalid-feedback">
							{% for error in form.commentaire.errors %}
								<span>{{ error }}</span>
							{% endfor %}
						</div>
							
					{% else %}
						{{ form.commentaire(class="form-control form-control-lg") }}						
					{% endif %}
				</div>
			</fieldset>
			<div class="form-group">
				{{ form.submit(class="btn btn-outline-info") }}
			</div>
		</form>

{% endblock content %}

Acheteur_Malin/acheteurmalin/templates/hightech.html
{% extends "categories.html" %}
{% block infotop %}
	
	

	<div class="infocontainer">
		<h2 class="texte nomarge">AcheteurMalin : </h2>
		<H1 class="texte h1">Information, conseil et comparatif achat.</H1>
		<img class= "courbe contenu" src="static/image/téléchargement.png" alt="courbe statistiques des prix">	
		<div class = infocontainer2>
			<H2 class="texte contenu">Retrouvez les objets les plus vendus du moment dans 			chaque catégorie. Comparez les au courbes des prix
				enregistré pour savoir combien vous devriez dépenser et ainsi éffectué un achat malin. En effet les statistiques de 
				masse permette de se faire une idée réaliste et pertinente de l’investissement à éffectuer.
			</H2>
		</div>
	</div>


{% endblock infotop %}

Acheteur_Malin/acheteurmalin/templates/layout.html
<!DOCTYPE html>
<html>
<head>
	<!-- Required meta tags notamment pour les portables-->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">
     <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='objet.css') }}">
  	 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='mediaQ.css') }}">
  
     <link href="https://fonts.googleapis.com/css?family=Open+Sans|Vollkorn&display=swap" rel="stylesheet">

     <link rel="shortcut icon" href="static/image/favicon.ico">

	{% if title %}
	 	<title>AcheteurMalin - {{ title }}</title>
	{% else %}
		<title>AcheteurMalin</title>
	{% endif %}

	{% if description %}
	<meta name="description" content="{{ description }}">
	{% else %}
	<meta name="description" content="Comparez les informations sur les ventes de produit. Suivez nos conseil pour éffectuer des achats malins. Information, conseil et comparatif achat.">
	{% endif %}

</head>
<body>	

			<div class=background></div>

			<header class= "topwrap">
				
				<div class="topnav">
					<img class= "logo navelement" src="static/image/flamme.png" alt="logo en forme de flamme">				
					<a class= "navelement"  href="{{ url_for('categories.accueil') }}">AcheteurMalin</a>
					<a class="navelement" href="{{ url_for('categories.accueil') }}">Accueil</a>
					    
					<div class="subnavbtn">
						<p class="navelement" href="{{ url_for('categories.accueil') }}">Catégories</p>
					</div>

					<a class="navelement" href="{{ url_for('main.enregistrer') }}">Enregistrer</a>
						
					<div class="subnav-content">
						<a href="{{ url_for('categories.hightech') }}">Hightech</a>
						<a href="{{ url_for('categories.musique') }}">Musique</a>
						<a href="{{ url_for('categories.electromenager') }}">Electroménager</a>
						<a href="{{ url_for('categories.telephone') }}">Téléphone</a>
					</div>
				</div>
				
			</header>

			<main role="main" class="wrapcontent">
				{% with messages = get_flashed_messages(with_categories=true) %}
			    	{% if messages %}
			    		{% for category, message in messages %}
			    		<div class="alert alert-{{ category }}">
			    			{{ message }}
			    		</div>
			    		{% endfor %}
			    	{% endif %}
			    {% endwith %}
				{% block content %}{% endblock %}
			</main>
			
		<!--<footer class="footer">
			<p>c 2019 Suivi des Tendances - </p>
			<a href="{{ url_for('main.mentionslegales') }}"> mentions légales</a>
		</footer>-->
	
</body>
</html>

Acheteur_Malin/acheteurmalin/templates/mentionslegales.html
{% extends "layout.html" %}
{% block content %}

	<div class="infocontainer">
		<h2 class="texte">AcheteurMalin : </h2>
		<H1 class="texte">Information, conseil et comparatif achat.</H1>
		<H2 class="texte">Retrouvez les objets les plus vendus du moment dans chaque catégorie. Comparez les au courbes des prix
enregistré pour savoir combien vous devriez dépenser et ainsi éffectué un achat malin. En effet les statistiques de 
masse permette de se faire une idée réaliste et pertinente de l’investissement à éffectuer.</H2>
	</div>

	<div class="objetcontainer">
		{% if objet[0] %}
			<div class="objet objet1">
				<img class= "photo" src="static/objet_photo\37ca375f8ca9d2f9.jpg" alt="photo de l'{{ objet[0].nom }}">
				<h3 class="texteobjet nomobjet" href=#>{{ objet[0].nom }}</h3> 
				<a class="texteobjet prixobjet" href=#>{{ objet[0].affiliation }}</a>	
				<a class="texteobjet commentaire" href=#>{{ objet[0].commentaire }}</a>  
			</div>
		{% endif %}

		{% if objet[1] %}
			<div class="objet objet2">
				<img class= "photo" src="/acheteurmalin/static/objet_photo/37ca375f8ca9d2f9.jpg" alt="photo de l'{{ objet[1].nom }}">
				<h3 class="texteobjet nomobjet" href=#>{{ objet[1].nom }}</h3> 
				<a class="texteobjet prixobjet" href=#>{{ objet[1].affiliation }}</a>	
				<a class="texteobjet commentaire" href=#>{{ objet[1].commentaire }}</a> 
			</div>
		{% endif %}

		{% if objet[2] %}
			<div class="objet objet3">
				<img class= "photo" src="{{ objet[2].image_file }}" alt="photo de l'{{ objet[2].nom }}">
				<h3 class="texteobjet nomobjet" href=#>{{ objet[2].nom }}</h3> 
				<a class="texteobjet prixobjet" href=#>{{ objet[2].affiliation }}</a>	
				<a class="texteobjet commentaire" href=#>{{ objet[2].commentaire }}</a> 
			</div>
		{% endif %}

		{% if objet[3] %}
			<div class="objet objet4">
				<img class= "photo" src="{{ objet[3].image_file }}" alt="photo de l'{{ objet[3].nom }}">
				<h3 class="texteobjet nomobjet" href=#>{{ objet[3].nom }}</h3> 
				<a class="texteobjet prixobjet" href=#>{{ objet[3].affiliation }}</a>	
				<a class="texteobjet commentaire" href=#>{{ objet[3].commentaire }}</a> 
			</div>
		{% endif %}

		{% if objet[4] %}
			<div class="objet objet5">
				<img class= "photo" src="{{ objet[4].image_file }}" alt="photo de l'{{ objet[4].nom }}">
				<h3 class="texteobjet nomobjet" href=#>{{ objet[4].nom }}</h3> 
				<a class="texteobjet prixobjet" href=#>{{ objet[4].affiliation }}</a>	
				<a class="texteobjet commentaire" href=#>{{ objet[4].commentaire }}</a> 
			</div>
		{% endif %}

		{% if objet[5] %}
			<div class="objet objet6">
				<img class= "photo" src="{{ objet[5].image_file }}" alt="photo de l'{{ objet[5].nom }}">
				<h3 class="texteobjet nomobjet" href=#>{{ objet[5].nom }}</h3> 
				<a class="texteobjet prixobjet" href=#>{{ objet[5].affiliation }}</a>	
				<a class="texteobjet commentaire" href=#>{{ objet[5].commentaire }}</a> 
			</div>
		{% endif %}

	</div>

{% endblock content %}

Acheteur_Malin/acheteurmalin/templates/musique.html
{% extends "categories.html" %}
{% block infotop %}
	
	

	<div class="infocontainertest">
		<h2 class="texte nomarge">AcheteurMalin : Qu'est ce que c'est ?</h2>
		<H1 class="texte h1">Information, conseil et comparatif achat.</H1>
		<div class = infocontainer2>
			<H2 class="texte contenu">Retrouvez les objets les plus vendus du moment dans 			chaque catégorie. Comparez les au courbes des prix
				enregistré pour savoir combien vous devriez dépenser et ainsi éffectué un achat malin. En effet les statistiques de 
				masse permette de se faire une idée réaliste et pertinente de l’investissement à éffectuer.
			</H2>
		</div>
		
		<img class= "courbe contenu" src="static/image/téléchargement.png" alt="courbe statistiques des prix">	
	</div>


{% endblock infotop %}

Acheteur_Malin/acheteurmalin/templates/telephone.html
{% extends "categories.html" %}
{% block infotop %}
	
	

	<div class="infocontainer">
		<h2 class="texte nomarge">AcheteurMalin : </h2>
		<H1 class="texte h1">Information, conseil et comparatif achat.</H1>
		<img class= "courbe contenu" src="static/image/téléchargement.png" alt="courbe statistiques des prix">	
		<div class = infocontainer2>
			<H2 class="texte contenu">Retrouvez les objets les plus vendus du moment dans 			chaque catégorie. Comparez les au courbes des prix
				enregistré pour savoir combien vous devriez dépenser et ainsi éffectué un achat malin. En effet les statistiques de 
				masse permette de se faire une idée réaliste et pertinente de l’investissement à éffectuer.
			</H2>
		</div>
	</div>


{% endblock infotop %}